### ISSUE TITLE
Feature Request: List Differences from -data-science

### ISSUE THREAD

**Issue by mikezawitkowski** [mkrapp/cookiecutter-reproducible-science#2]
The README.md right now starts with (bold emphasis mine): 

> A boilerplate for reproducible and transparent science with **close resemblances** to the philosophy of Cookiecutter Data Science: ...

I would find it very helpful if you could list out what the key differences are between this cookiecutter and the cookiecutter-data-science repo. (https://drivendata.github.io/cookiecutter-data-science/)

I've been thinking of making my own cookiecutter that fits more with my workflow than cookiecutter-data-science but you may have already made the changes that make the original repo a little clunky to me. It's not easy to tell from your documentation though..

Thanks!

**Comment by mkrapp** [comment]
Good idea. I'll add a visual for the directory structure, similar to the one provided in the `README.md` of the `cookie cutter-data-science`
