### ISSUE TITLE
DOC: add a `cookiecutter`, `cookiecutter-template` labels to the github project

### ISSUE THREAD

**Issue by westurner** [mkrapp/cookiecutter-reproducible-science#6]
- [x] add a `cookiecutter` & `cookiecutter-template` labels to the github project

  see: https://github.com/cookiecutter/cookiecutter#a-pantry-full-of-cookiecutters

see also: https://github.com/drivendata/cookiecutter-data-science/issues/239

**Comment by mkrapp** [comment]
Done. Thanks, @westurner.

**Comment by westurner** [comment]
Thanks
